version: '3.9'

services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - 7777:7777
    depends_on:
      - db
    volumes:
      - postgres-data:/app/postgres-data
    environment:
      DATABASE_URL: postgresql://postgres:root@host.docker.internal:5432/medical?schema=public

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=medical
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data:
